data:
  image_dirs:     
    - ./dataverse_files/HAM10000_images_part_1
    - ./dataverse_files/HAM10000_images_part_2
  metadata_path: "./dataverse_files/HAM10000_metadata"
  image_size: 256
  val_split: 0.2
  test_image_dir: "./dataverse_files/ISIC2018_Task3_Test_Images"
  test_metadata_path: "./dataverse_files/ISIC2018_Task3_Test_GroundTruth.csv"
  num_workers: 2
  seed: 42

train_autoencoder:
  epochs: 100
  batch_size: 32
  learning_rate: 0.01
  weight_decay: 0.001
  patience: 10
  beta_max: 50
  silhouette_weight: 10
  center_loss_weight: 1.0
  beta_midpoint: 10
  beta_steepness: 0.3
  freeze_patience: 3
  min_delta: 0.001
  noise_level: 0.3
  save_path: "./save_model_autoencoder/autoencoder.pt"
  save_reconstruction: "./reconstructions"

train_classifier:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.001
  batch_size: 32
  save_path: "./save_model_classifier/classifier.pt"

test_classifier:
  batch_size: 32
  embeddings_path: "./save_model_embeddings/embeddings.pt"
  classifier_path: "./save_model_classifier/classifier.pt"

class_names:
  - akiec
  - bcc
  - bkl
  - df
  - mel
  - nv
  - vasc

latent_dim: 256