data:
  image_dirs:     
  - ./dataverse_files/HAM10000_images_part_1
  - ./dataverse_files/HAM10000_images_part_2
  metadata_path: "./dataverse_files/HAM10000_metadata"
  image_size: 256
  val_split: 0.15
  test_split: 0.15

training:
  batch_size: 32
  num_workers: 4
  seed: 42

train_autoencoder:
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 5
  min_delta: 0.01
  save_path: "./salve_model/autoencoder.pth"
  